version: '3.8'

services:

  pfm_mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  pfm_mongodb:
    image: mongo
    
#network section
networks:
  default:
    name: psl-pfm-network
    driver: bridge
    
#volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data
  mongo_data:
    name: mongo_data
