version: '3.8'

services:

  #mssqldb: sql server
  pfm_mssqldb:
    container_name: pfm_mssqldb
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1438:1433"
  
  #pfm_mongodb: mongo
  pfm_mongodb:
    container_name: pfm_mongodb
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db