version: '3.8'

services:

  pfm_mssqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  pfm_mongodb:
    image: mongo
    
  pfm_redisdb:
    image: redis:alpine
  #microservices api section
  pfm.api:
    image: ${DOCKER_REGISTRY-}pfm-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: PersonalFinancialManagement.API/Dockerfile
    
#network section
networks:
  default:
    name: psl-pfm-network
    driver: bridge
    
#volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data
  mongo_data:
    name: mongo_data
