version: "3.8"

services:
    #mssqldb: sql server
    pfm_mssqldb:
        container_name: pfm_mssqldb
        environment:
            SA_PASSWORD: "Admin@123"
            ACCEPT_EULA: "Y"
        restart: always
        volumes:
            - sqlserver_data:/var/lib/sqlserver/data
        ports:
            - "127.0.0.1:1438:1433"

    #pfm_mongodb: mongo
    pfm_mongodb:
        container_name: pfm_mongodb
        restart: always
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ports:
            - "27018:27017"
        volumes:
            - mongo_data:/data/db
    #redisdb: redis
    pfm_redisdb:
        container_name: pfm_redisdb
        restart: always
        ports:
            - "6379:6379"

  #microservices api sections
    pfm.api:
        container_name: pfm.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:80
            - "ConnectionStrings:DefaultConnection=Server=pfm_mssqldb,1433;Database=personal_financial_management;User Id=sa;Password=Admin@123;TrustServerCertificate=True"
            - "ConnectionStrings:MigrationConnection=Server=pfm_mssqldb,1433;Database=personal_financial_management;User Id=sa;Password=Admin@123;TrustServerCertificate=True"
            - "MongoDbSettings:ConnectionString=mongodb://pfm_mongodb:27018"
            - "ElasticConfiguration:Uri=http://elasticsearch:9200"
            - "Serilog:WriteTo:2:args:connectionstring=Server=pfm_mssqldb,1433;Database=personal_financial_management;User Id=sa;Password=Admin@123;TrustServerCertificate=True"
            - "Serilog:WriteTo:3:args:nodeuris=http://elasticsearch:9200"
        depends_on: 
            - pfm_mssqldb
            - kibana
        ports:
            - "6002:80"
        restart: always
    elasticsearch:
        container_name: elasticsearch
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - xpack.security.enabled=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        #      - ELASTIC_USERNAME=elastic #default username
            - ELASTIC_PASSWORD=admin
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
    kibana:
        container_name: kibana
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=elastic
            - ELASTICSEARCH_PASSWORD=admin
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"
        healthcheck:
            test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
            interval: 30s
            timeout: 10s
            retries: 5
